### ISSUE TITLE
Laps API end point, returns an error for certain laps

### ISSUE THREAD

**Issue by michaelphillpotts** [br-g/openf1#134]
Using https://api.openf1.org/v1/laps?session_key=9662&driver_number=4&lap_number=1

I get a generic error message and a stack trace . This happens for all drivers for lap 1

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/openf1/services/gateway/app.py", line 109, in forward_query
    save_to_cache(path=path, params=params, results=results)
  File "/app/openf1/services/gateway/cache.py", line 118, in save_to_cache
    is_long_term_results = _is_long_term_results(
  File "/app/openf1/services/gateway/cache.py", line 58, in _is_long_term_results
    latest_date = _get_results_latest_date(results)
  File "/app/openf1/services/gateway/cache.py", line 44, in _get_results_latest_date
    date = str_to_datetime(val)
  File "/app/openf1/util.py", line 88, in str_to_datetime
    dt = parser.parse(s, fuzzy=True)
  File "/usr/local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 640, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 719, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/usr/local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 201, in split
    return list(cls(s))
  File "/usr/local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 69, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not NoneType
```

Expected result is JSON data, e.g. https://api.openf1.org/v1/laps?session_key=9662&driver_number=55&lap_number=2

**Comment by br-g** [comment]
Thank you for reporting this.    
This issue has been addressed in the latest version, which is currently live at http://dev.openf1.org. The fix will be rolled out to http://api.openf1.org shortly.
